// GENERATED by clanker-arena/tools/gen-moves-preview.mjs — do not edit by hand.
//
// The game's move names, 24 of them across 8 types, so a cat in the preview
// swings the moves it would really swing.
//
// NAMES ONLY, on purpose. Power, accuracy and kind are balance data and live with
// the game; the strength and weakness tables are not public at all. A cat here is
// only borrowing the vocabulary.

export const MOVES_BY_TYPE: Record<string, readonly string[]> = {
  "ZOOMIES": ["Zoom", "Taze", "Live Wire"],
  "FORGE": ["Lighter Spark", "Open Flame", "Propain"],
  "COOLANT": ["Spritz Mist", "Water Hose", "Hang-Ten"],
  "SIGNAL": ["Ping", "DDOS", "ALT-F4"],
  "GLITCH": ["Lag_switch", "File_Corruption", "Null_Pointer"],
  "CRYO": ["Chill", "Frostbite", "Brain Freeze"],
  "SCRAP": ["Swipe", "Junk Throw", "a Steel Chair"],
  "STRAY": ["Shiv", "Body Check", "Say Uncle."],
}

/** Every move, for anything that does not care about type. */
export const ALL_MOVES: readonly string[] =
  Object.values(MOVES_BY_TYPE).flat()

/** The moves a cat of this type can swing, falling back to the whole list. */
export const movesFor = (type: string): readonly string[] =>
  MOVES_BY_TYPE[type] ?? ALL_MOVES
